Tutorial doc 
https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [1]:
import numpy as np
import torch

## Initializing Tensors

In [2]:
data = [[1, 2], [3, 4]]
print(data)
print(type(data))
x_data = torch.tensor(data)
print(x_data)
print(type(x_data))

[[1, 2], [3, 4]]
<class 'list'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [3]:
np_array = np.array(data)
print(np_array)
print(type(np_array))

x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]])


In [15]:
x = np.array([1, 2, 3])
x_t = torch.tensor(x)
print(x.shape)
print(x_t.shape)


X = np.array([[2, 4, 8], [6, 8, 0]])
X_t = torch.tensor(X)
print(X.shape)
print(X_t.shape)

(3,)
torch.Size([3])
(2, 3)
torch.Size([2, 3])


### From another tensor.

In [8]:
x_ones = torch.ones_like(x_data) # retain the same data type
print(f"Ones Tensor:\n {x_ones}")
x_rand = torch.rand_like(x_data, dtype=torch.float) # converts dtype to float
print(f"Random Tensor:\n {x_rand}")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])
Random Tensor:
 tensor([[0.1032, 0.4314],
        [0.5311, 0.6445]])


In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6995, 0.1993, 0.9549],
        [0.0694, 0.0375, 0.9176]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [16]:
tensor = torch.rand(3, 4)

print(tensor)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.2015, 0.9825, 0.2383, 0.0833],
        [0.2973, 0.2988, 0.0319, 0.9250],
        [0.8749, 0.0367, 0.5628, 0.0192]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensor
Pytorch supports various mathematical ops on tensors and we can also move these tensors to `Accelerators` if available to speeden up the computation.

By default it uses cpu, we need to explicitly move to GPUs.

Few methods to check accelerators and move tensors to them.

https://docs.pytorch.org/docs/stable/torch.html#accelerators

In [17]:
print("Does this device has any accelerators?", torch.accelerator.is_available())
print("Current Accelerator available", torch.accelerator.current_accelerator())

Does this device has any accelerators? True
Current Accelerator available mps


In [19]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

the tensor is not shifted to accelerator, check `device` in below output.

In [20]:
tensor

tensor([[0.2015, 0.9825, 0.2383, 0.0833],
        [0.2973, 0.2988, 0.0319, 0.9250],
        [0.8749, 0.0367, 0.5628, 0.0192]], device='mps:0')

### Some operations

In [29]:
tensor = torch.ones(4, 4)
print(f"First row {tensor[0]}")
print(f"First column {tensor[:, 0]}")
print(f"Last column {tensor[:, -1]}")
tensor[:, 1] = 0
tensor[1, -1] = 9
print(tensor)


First row tensor([1., 1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 9.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Joining Tensors

In [31]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim = 0 stacks vertically and dim =1 horizontally
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 9., 1., 0., 1., 9., 1., 0., 1., 9.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [33]:
y1 = tensor @ tensor.T
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

# another way
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor([[ 3., 11.,  3.,  3.],
        [11., 83., 11., 11.],
        [ 3., 11.,  3.,  3.],
        [ 3., 11.,  3.,  3.]])
tensor([[ 3., 11.,  3.,  3.],
        [11., 83., 11., 11.],
        [ 3., 11.,  3.,  3.],
        [ 3., 11.,  3.,  3.]])
tensor([[ 3., 11.,  3.,  3.],
        [11., 83., 11., 11.],
        [ 3., 11.,  3.,  3.],
        [ 3., 11.,  3.,  3.]])


In [34]:
tensor*tensor # element wise

tensor([[ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1., 81.],
        [ 1.,  0.,  1.,  1.],
        [ 1.,  0.,  1.,  1.]])

### Single element tensor

this will be helpful when we get a single element like some output number after aggreation ops on a tensor

In [37]:
agg = tensor.sum() # sums all elements of a tensor
print(agg, type(agg))

agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(20.) <class 'torch.Tensor'>
20.0 <class 'float'>


#### In place operations 
ends with `_`

In [38]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 9.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[ 6.,  5.,  6.,  6.],
        [ 6.,  5.,  6., 14.],
        [ 6.,  5.,  6.,  6.],
        [ 6.,  5.,  6.,  6.]])


##### Tensors and Numpy have bridge, changes in either of them reflect on the other one.

In [39]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [40]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
