## nn Module in PyTorch

`nn` module is one of the fundamental part of training neural networks in PyTorch.

in the pipeline use builtin
- module
- activation
- loss
- optim

In [1]:
import torch
import torch.nn as nn

In [2]:
# create model class from nn super class

class Model(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        
        # 1 layer with 1 neuron -- as compared to manual, w and b are computed by Linear class
        self.linear = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        z = self.linear(features)
        y_pred = self.sigmoid(z)
        
        return y_pred

In [3]:
features = torch.rand(10, 5) # 10 examples with 5 features

In [4]:
model = Model(features.shape[1])

NOTE:
`model.forward(features)` works but pytorch recommends calling `model(features)` directly, and nn module has implemented magic function for `__call__`

In [5]:
model(features)

tensor([[0.6253],
        [0.6683],
        [0.6477],
        [0.5832],
        [0.6089],
        [0.6610],
        [0.7234],
        [0.6655],
        [0.6457],
        [0.6219]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[ 0.3697,  0.3238,  0.1929, -0.2332,  0.0563]], requires_grad=True)

### A more complex neural network
with some hidden layers

In [7]:
# create model class from nn super class

class ComplexModel(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        # layer 1 has 3 neurons
        self.linear1 = nn.Linear(in_features=num_features, out_features=3)
        self.relu = nn.ReLU()
        
        # layer 2 has 1 neuron
        self.linear2 = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        z1 = self.linear1(features)
        a1 = self.relu(z1)
        
        z2 = self.linear2(a1)
        y_pred = self.sigmoid(z2)

        return y_pred

In [8]:
complex_model = ComplexModel(features.shape[1])

In [9]:
complex_model(features)

tensor([[0.5074],
        [0.5089],
        [0.5081],
        [0.4850],
        [0.4458],
        [0.5056],
        [0.5024],
        [0.4464],
        [0.5065],
        [0.4340]], grad_fn=<SigmoidBackward0>)

In [10]:
complex_model.linear1.weight

Parameter containing:
tensor([[-0.1987,  0.1089,  0.4081,  0.1977, -0.3703],
        [ 0.0808, -0.1483,  0.0269, -0.0585,  0.3164],
        [ 0.2575,  0.3264,  0.2726,  0.3346, -0.1233]], requires_grad=True)

In [12]:
print(complex_model)

ComplexModel(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [13]:
from torchinfo import summary

In [14]:
summary(complex_model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ComplexModel                             [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### More simpler way of creating network

In [15]:
# create model class from nn super class

class ComplexModel(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        y_pred = self.network(features)
        return y_pred

In [16]:
model = ComplexModel(features.shape[1])

In [17]:
summary(complex_model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ComplexModel                             [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00